name: Jira Deployment (Org Repo)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fake deploy step
        run: echo "Deploying for SCRUM-6 ..."

      - name: Report deployment to Jira
        uses: atlassian/gajira-deployment@v2
        with:
          environment: "staging"   # dev / staging / prod
          state: "successful"
        env:
          JIRA_SITE: "lemaithy222.atlassian.net"
          JIRA_USER_EMAIL: "lemaithy222@gmail.com"
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
